
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
       docker build . -t ${{secrets.DOCKER_USERNAME}}/workflows:v1-nextjs
       echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin 
       docker push ${{secrets.DOCKER_USERNAME}}/workflows:v1-nextjs